version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crossaudit
    volumes:
      - db-data:/var/lib/postgresql/data
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - gateway
volumes:
  db-data:
