[package]
name = "crossaudit-billing"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0"
deadpool-postgres = "0.13"
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
