name: ci
on: [push, pull_request]
jobs:
  rust:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: secret
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - run: psql ${{env.DATABASE_URL}} -f sql/0001_init.sql && psql ${{env.DATABASE_URL}} -f sql/0002_dataroom.sql
      - run: cargo test --workspace
      - run: cargo test --workspace --no-default-features
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm --prefix web install
      - run: pnpm --prefix web build
  cypress:
    runs-on: ubuntu-latest
    needs: [web]
    steps:
      - uses: cypress-io/github-action@v5
        with:
          start: pnpm --prefix web dev
          wait-on: http://localhost:3000
  docker-sign:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: docker build -f docker/Dockerfile.gateway -t ghcr.io/example/crossaudit-gateway:${{github.sha}} .
      - run: cosign sign --key env://COSIGN_KEY ghcr.io/example/crossaudit-gateway:${{github.sha}}
